# SPDX-FileCopyrightText: no
# SPDX-License-Identifier-Identifier: CC0-1.0
#
# Unsquash / unpack a filesystem. Multiple sources are supported
# aarch64: source path adjusted for this ISO's arch directory
---

unpack:
    -   source: /run/archiso/bootmnt/arch/aarch64/airootfs.sfs
        sourcefs: squashfs
        destination: /
